name: Deploy Sphinx documentation to Pages

on:
  workflow_dispatch:
  push:
    branches: [master] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Doxygen install
      run: sudo apt-get install -y doxygen
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate Doxygen
      run: cd docs && doxygen Doxyfile
    - name: Generate Sphinx rst files
      run: cd docs && mkdir api && python generate_rst.py
    - name: Deployment
      uses: sphinx-notes/pages@v3
      with:
        checkout: false